### Use NumPy arrays to analyze weather data (temperature, humidity, rainfall). Perform operations  such  as  reshaping,  broadcasting,  and  calculating  statistical  measures (mean, median, variance, standard deviation). Compare results with built-in Python functions. 

In [1]:
import numpy as np
import pandas as pd


In [2]:
# Generate random synthetic weather data for 365 days (1 year)
np.random.seed(42)

temperature = np.random.normal(loc=30, scale=5, size=365)   # mean 30°C, std 5
humidity = np.random.uniform(low=40, high=90, size=365)     # 40–90% range
rainfall = np.random.gamma(shape=2, scale=5, size=365)      # skewed rainfall data

# Stack into a single 2D array: rows=days, cols=features
weather_data = np.column_stack((temperature, humidity, rainfall))

print("Shape of weather data:", weather_data.shape)
print("First 5 records:\n", weather_data[:5])



Shape of weather data: (365, 3)
First 5 records:
 [[32.48357077 51.17979193  6.00249807]
 [29.30867849 88.16112697  7.98775174]
 [33.23844269 40.60772373 26.87272059]
 [37.61514928 88.49394134 17.92562019]
 [28.82923313 42.1579956   6.71537749]]


In [3]:
# Create data for 3 years by repeating the single year data
weather_3yrs = np.tile(weather_data, (3, 1))  # Repeat the data 3 times
weather_3yrs = weather_3yrs.reshape(3, 365, 3)  # Now reshape to (years, days, features)
print("Shape after reshaping (years, days, features):", weather_3yrs.shape)

# Broadcasting example — convert Celsius to Fahrenheit for temperature
temp_celsius = weather_data[:, 0]
temp_fahrenheit = temp_celsius * 9/5 + 32

# Add it back as a new column
weather_extended = np.column_stack((weather_data, temp_fahrenheit))
print("Shape after broadcasting new feature:", weather_extended.shape)

Shape after reshaping (years, days, features): (3, 365, 3)
Shape after broadcasting new feature: (365, 4)


In [4]:
# Mean, Median, Variance, Standard Deviation using NumPy
mean_vals = np.mean(weather_data, axis=0)
median_vals = np.median(weather_data, axis=0)
variance_vals = np.var(weather_data, axis=0)
std_vals = np.std(weather_data, axis=0)

print("📊 NumPy Statistical Measures")
print(f"Mean: {mean_vals}")
print(f"Median: {median_vals}")
print(f"Variance: {variance_vals}")
print(f"Std Dev: {std_vals}")


📊 NumPy Statistical Measures
Mean: [30.04973201 65.07275711 10.69317116]
Median: [30.29104359 65.17086354  9.22145435]
Variance: [ 22.40846    208.82772437  50.90008059]
Std Dev: [ 4.73375749 14.45087279  7.13442924]


In [5]:
# Convert columns to Python lists
temp_list = temperature.tolist()
humidity_list = humidity.tolist()
rainfall_list = rainfall.tolist()

# Calculate using built-in Python functions
mean_builtin = [sum(x)/len(x) for x in [temp_list, humidity_list, rainfall_list]]
median_builtin = [sorted(x)[len(x)//2] for x in [temp_list, humidity_list, rainfall_list]]
variance_builtin = [
    sum((i - np.mean(x))**2 for i in x) / len(x)
    for x in [temp_list, humidity_list, rainfall_list]
]
std_builtin = [v**0.5 for v in variance_builtin]

print("🧮 Built-in Python Function Results")
print(f"Mean: {mean_builtin}")
print(f"Median: {median_builtin}")
print(f"Variance: {variance_builtin}")
print(f"Std Dev: {std_builtin}")


🧮 Built-in Python Function Results
Mean: [30.04973201106029, 65.07275711180509, 10.693171155347287]
Median: [30.29104359223, 65.17086354274285, 9.221454353404845]
Variance: [np.float64(22.408460002000908), np.float64(208.82772436899705), np.float64(50.90008059329659)]
Std Dev: [np.float64(4.73375749294373), np.float64(14.45087278917772), np.float64(7.134429240892126)]
